# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cesar Enrique Barboza Selix
title: Student at Informatics Engineering
email: hoadelete@hotmail.com
# email_title: Email (Email title override)
phone: (+52)3313462954
# phone_title: Phone (Phone title override)
website: https://lightworker0923.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  Lightworker0923
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: caesarmadboy
linkedin_username: https://www.linkedin.com/in/cesar-barboza-299194264/
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/ME.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there It's Caesar here! a little bit of myself is that I am a future kind of software engineer who loves learn and share knoledgments with others to build cool stuff that wants to mark and put my grain sand in software companies to grow up as society and help others in their needs and provide them tranquility and comfort as empatethic and helper human I am. I'm still training myself on software area looking passionately to give my best

content:
  - title: Certifications
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: White Belt
        sub_title: By Lean & Six Sigma
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #link_text: Link Text
        #additional_links:
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
       #quote: >
          #Short overview of the project (optional)
        #description: | # this will include new lines to allow paragraphs
          #Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: top-right
        title: Teleperformance
        sub_title: Assitant on Customer Service
        caption: November 2020 - December 2021
        #link: Link to company (optional)
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Customer Service Assistant specialized in bank credit cards databases, communication skills and English level were highly improved, I got acquainted with some data systems.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Universidad De Guadalajara
        sub_title: Current Student at Informatics Engineering, ending on mid 2024.
        caption: Current Schedule L-V 3PM - 9PM (till december 2023)
        quote: >
          Data managment, included Data Bases, servers, web services and a little bit of Develop on Java and Python.
        description: | # this will include new lines to allow paragraphs
          Jr. developer on data managment mentioned previosly.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I'm a 21*yo* guy passionate on everything around getting **Knowledgment** I enjoy to draw, I went to a drawing school several years ago, I like to write about anything I'm a god editor and argumentator, I am a big fan of women, I feel better when people is around to speak about literally everything, I love to learn anything from everyone and every experience I got.

      I love co-work with people who seem like me to build cool stuff.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
